import "styles/globals.scss";
import "./styles/main.scss";
import Providers from "util/themeProvider";
import { Noto_Sans_KR } from "next/font/google";
import type { Metadata } from "next";
import { Footer, Header } from "./components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const myFont = Noto_Sans_KR({
  weight: ["500"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <body className={myFont.className}>
          <Providers>
            <Header />
            <main>{children}</main>
            <Footer />
          </Providers>
        </body>
      </html>
    </>
  );
}
