import "styles/globals.scss";
import styles from "./styles/page.module.scss";
import { Noto_Sans_KR } from "next/font/google";
import type { Metadata } from "next";
import { Footer, Header, NavBar } from "./components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const myFont = Noto_Sans_KR({
  weight: ["500"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning={true}>
        <body className={myFont.className}>
          <Header />
          <main className={styles.main}>
            <nav className={styles.nav}>
              <NavBar />
            </nav>
            {children}
            <section />
          </main>
          <Footer />
        </body>
      </html>
    </>
  );
}
